/* ═════════════════════════════════════════════════════════════════════
   ZENTRALE KUNSTWERK-DATENQUELLE
   ─────────────────────────────────────────────────────────────────────
   Alle Kunstwerke der Galerie werden aus diesem einen Array geladen
   (siehe script.js: renderGallery / renderFeatured / openArtworkModal).

   NEUES KUNSTWERK HINZUFÜGEN:
   1. Bilddatei in den Ordner "Images/" legen.
   2. Ein neues Objekt unten in ARTWORKS einfügen (Vorlage kopieren).
   3. Felder ausfüllen. Wenn eine Information (noch) nicht vorhanden ist,
      den Platzhaltertext einfach stehen lassen oder durch den echten
      Text ersetzen — nichts an Layout/Code muss angefasst werden.

   FELDER:
   id                → eindeutiger, URL-freundlicher Schlüssel (kebab-case)
   title             → Titel des Kunstwerks
   image             → Pfad relativ zur index.html, z. B. "Images/Datei.jpeg"
   alt               → Alternativtext für Screenreader/SEO (Bild sachlich beschreiben)
   year              → Entstehungsjahr
   category          → "glaube"   = Glaube & Symbolik
                        "tiere"   = Tiere & Natur
                        "portrait"= Porträt & Stille Momente
   categoryLabel     → sichtbarer Kategorie-Name (Deutsch)
   technique         → Material/Technik
   dimensions        → Maße, z. B. "60 × 80 cm"
   background        → Entstehungsgeschichte des Werks
   symbolism         → Bedeutung von Farben, Formen, Symbolen
   christianMeaning  → christliche Botschaft des Werkes
   bibleVerse        → passende Bibelstelle (Text + Referenz)
   interpretation    → persönliche Deutung/Intention der Künstlerin
   availability      → "Verfügbar" | "Verkauft" | "Privatsammlung" | "Auf Anfrage"
   featured          → true = erscheint im "Ausgewählte Werke"-Bereich der Startseite
═════════════════════════════════════════════════════════════════════ */

const PLACEHOLDER = {
  background: "Die Entstehungsgeschichte dieses Werkes wird in Kürze ergänzt.",
  symbolism: "Eine Beschreibung der verwendeten Farben, Formen und Symbole folgt in Kürze.",
  christianMeaning: "Die christliche Botschaft dieses Werkes wird in Kürze ergänzt.",
  bibleVerse: "",
  interpretation: "Die persönliche Deutung der Künstlerin wird in Kürze ergänzt.",
  dimensions: "Maße auf Anfrage",
  technique: "Technik wird ergänzt",
};

const ARTWORKS = [
  // ── GLAUBE & SYMBOLIK ────────────────────────────────────────────
  {
    id: "loewe-von-juda-I",
    title: "Löwe von Juda",
    image: "Images/IMG_1125.jpeg",
    alt: "Gemälde eines Löwenprofils mit wehender Mähne in Gold- und Erdtönen, mit Blattgold-Akzenten",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Blattgold auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Die goldenen Akzente in der Mähne greifen das Licht ein und verleihen dem Tier eine königliche, fast überirdische Präsenz.",
    christianMeaning:
      "Der Löwe von Juda ist eines der ältesten christlichen Sinnbilder für Christus als König und Sieger.",
    bibleVerse: "„Siehe, es hat überwunden der Löwe, der da ist vom Stamm Juda.“ — Offenbarung 5,5",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "loewe-von-juda-II",
    title: "Löwe von Juda II",
    image: "Images/IMG_1165.jpeg",
    alt: "Gemälde eines Löwen von vorne mit ausdrucksstarkem Blick und heller Mähne",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning:
      "Als zweites Werk der Löwe-von-Juda-Reihe steht auch dieses Bild für Stärke, Würde und die königliche Seite des Glaubens.",
    bibleVerse: "„Siehe, es hat überwunden der Löwe, der da ist vom Stamm Juda.“ — Offenbarung 5,5",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "heiliger-geist",
    title: "Heiliger Geist",
    image: "Images/IMG_1575.jpeg",
    alt: "Gemälde einer weißen Taube mit ausgebreiteten Flügeln unter einem goldenen Kreis, in Creme- und Goldtönen",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Blattgold auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Die Taube mit ausgebreiteten Flügeln unter dem goldenen Kreis verweist auf Reinheit, Frieden und eine Gegenwart, die von oben herabkommt.",
    christianMeaning:
      "Die Taube ist das klassische Symbol des Heiligen Geistes, der bei der Taufe Jesu sichtbar herabkam.",
    bibleVerse:
      "„Und der Geist Gottes schwebte auf dem Wasser.“ — 1. Mose 1,2",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "anbetung",
    title: "Anbetung",
    image: "Images/IMG_1146.jpeg",
    alt: "Gemälde einer betenden Gestalt mit gefalteten Händen und goldenem Heiligenschein vor dunklem Hintergrund",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Blattgold auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Die gefalteten Hände und der gesenkte Blick stehen für Hingabe und stille Zwiesprache; der goldene Heiligenschein hebt die Gestalt aus dem Irdischen heraus.",
    christianMeaning:
      "Ein Bild der Anbetung — der bewussten Hinwendung des Herzens zu Gott im Gebet.",
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "dornenkrone",
    title: "Dornenkrone",
    image: "Images/IMG_1544.jpeg",
    alt: "Gemälde einer Dornenkrone vor hellem Hintergrund",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: "Die Dornenkrone erinnert an Leid, das getragen wurde, damit daraus Hoffnung erwachsen kann.",
    christianMeaning:
      "Die Dornenkrone ist eines der zentralen Passionssymbole und verweist auf das Leiden Christi am Kreuz.",
    bibleVerse:
      "„… und die Kriegsknechte flochten eine Krone aus Dornen und setzten sie auf sein Haupt.“ — Johannes 19,2",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: true,
  },
  {
    id: "das-kreuz",
    title: "Das Kreuz",
    image: "Images/IMG_1577.jpeg",
    alt: "Gemälde eines Kreuzes",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning:
      "Das Kreuz ist das zentrale Zeichen des christlichen Glaubens — Symbol von Opfer, Erlösung und Hoffnung zugleich.",
    bibleVerse:
      "„Das Wort vom Kreuz ist eine Torheit denen, die verloren werden; uns aber, die wir selig werden, ist es eine Gotteskraft.“ — 1. Korinther 1,18",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "das-schaf",
    title: "Das Schaf",
    image: "Images/IMG_1173.jpeg",
    alt: "Gemälde eines Schafes",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: "Das Schaf steht für Anvertrauen und die Geborgenheit, die in einer führenden Hand liegt.",
    christianMeaning:
      "Das Bild des Schafes, das einem Hirten folgt, ist eines der ältesten und zärtlichsten Bilder für die Beziehung zwischen Gott und Mensch.",
    bibleVerse: "„Der HERR ist mein Hirte, mir wird nichts mangeln.“ — Psalm 23,1",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "lamm",
    title: "Lamm",
    image: "Images/IMG_1196.jpeg",
    alt: "Gemälde eines Lammes",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: "Das Lamm steht für Unschuld und stellvertretendes Opfer.",
    christianMeaning:
      "Das Lamm Gottes ist eines der ältesten christlichen Christussymbole — Zeichen der Sanftmut und des Opfers, das Versöhnung schafft.",
    bibleVerse:
      "„Siehe, das ist Gottes Lamm, das der Welt Sünde trägt!“ — Johannes 1,29",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "kleines-lamm",
    title: "Kleines Lamm",
    image: "Images/IMG_1565.jpeg",
    alt: "Gemälde eines kleinen Lammes",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning:
      "Als Gegenstück zu „Lamm“ betont dieses kleinere, zartere Werk die Verletzlichkeit, die unter Gottes Schutz getragen wird.",
    bibleVerse: "„Er wird die Lämmer auf seinen Arm nehmen und im Busen tragen.“ — Jesaja 40,11",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "gehalten",
    title: "Gehalten",
    image: "Images/IMG_1548.jpeg",
    alt: "Gemälde zweier Hände, die ein kleines Lamm behutsam halten, darüber eine Dornenkrone als Heiligenschein",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Zwei Hände tragen behutsam ein Lamm; die Dornenkrone darüber verbindet Zartheit und Leid zu einem Bild bedingungsloser Fürsorge.",
    christianMeaning:
      "Ein Sinnbild dafür, dass niemand aus Gottes Hand fällt — gehalten, selbst dort, wo Dornen sind.",
    bibleVerse:
      "„Fürchte dich nicht, denn ich bin mit dir; weiche nicht, denn ich bin dein Gott.“ — Jesaja 41,10",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "ruhe",
    title: "Ruhe",
    image: "Images/IMG_1549.jpeg",
    alt: "Gemälde eines ruhenden Schafes in hellen, weichen Tönen",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: "Die ruhige Haltung des Tieres spiegelt einen Frieden, der von außen geschenkt wird, nicht selbst erzeugt.",
    christianMeaning: "Ein Bild der Ruhe, die entsteht, wenn man sich in Gottes Führung fallen lässt.",
    bibleVerse: "„Er weidet mich auf einer grünen Aue und führet mich zum frischen Wasser.“ — Psalm 23,2",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "unschuld",
    title: "Unschuld",
    image: "Images/IMG_1569.jpeg",
    alt: "Gemälde eines Lammes mit goldenem Kreuzanhänger und einer welken Rose",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl auf Leinwand mit aufgesetztem Kreuzanhänger und getrockneter Rose",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Das goldene Kreuz um den Hals des Lammes und die verwelkte Rose verbinden Reinheit mit der Vergänglichkeit des Irdischen.",
    christianMeaning:
      "Unschuld, die durch das Kreuz geschützt bleibt — selbst wenn alles andere vergeht.",
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "eva",
    title: "Eva",
    image: "Images/IMG_1194.jpeg",
    alt: "Gemälde mit dem Titel Eva",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning:
      "Eva steht in der biblischen Erzählung am Anfang der Menschheitsgeschichte — zwischen Erschaffung, Fall und der Hoffnung auf Erlösung.",
    bibleVerse: "„Und Gott schuf den Menschen ihm zum Bilde.“ — 1. Mose 1,27",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "aufbluehendes-herz",
    title: "Aufblühendes Herz",
    image: "Images/IMG_5202.jpg",
    alt: "Gemischte Medien: ein steinern strukturiertes Herz mit einem Riss, aus dem ein blühender Zweig mit weißen Blüten wächst",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Strukturpaste auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Das steinerne, narbige Herz trägt einen Riss — und genau aus diesem Riss wächst ein blühender Zweig. Bruch und neues Leben stehen nicht gegeneinander, sondern ineinander.",
    christianMeaning:
      "Ein Bild dafür, dass Gott aus einem verhärteten Herzen ein lebendiges macht — Verwandlung, die gerade dort beginnt, wo etwas zerbrochen ist.",
    bibleVerse:
      "„Und ich will euch ein neues Herz und einen neuen Geist in euch geben und will das steinerne Herz aus eurem Fleisch wegnehmen und euch ein fleischernes Herz geben.“ — Hesekiel 36,26",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "liebe",
    title: "Liebe",
    image: "Images/IMG_5207.jpg",
    alt: "Gemischte Medien: ein weißes Keramikherz mit der Prägung 'Liebe', umgeben von gemalten weißen Blütenzweigen vor Blattgold-Hintergrund",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Blattgold auf Leinwand mit Keramikherz",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Das plastische Keramikherz mit der Prägung „Liebe“ tritt aus der Fläche heraus, umrahmt von zart blühenden Zweigen vor Blattgold.",
    christianMeaning:
      "Die Liebe steht im Zentrum — nicht als Gefühl, sondern als das Wesen Gottes selbst, aus dem alles andere wächst.",
    bibleVerse: "„Gott ist Liebe.“ — 1. Johannes 4,8",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "danke",
    title: "Danke",
    image: "Images/IMG_5208.jpg",
    alt: "Gemischte Medien: ein weißes Keramikherz mit der Prägung 'Danke' und einer Feder, umgeben von gemalten Blütenzweigen vor Blattgold-Hintergrund",
    year: "2026",
    category: "glaube",
    categoryLabel: "Glaube & Symbolik",
    technique: "Acryl und Blattgold auf Leinwand mit Keramikherz",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Als Gegenstück zu „Liebe“ trägt dieses Herz das Wort „Danke“ — begleitet von einer leichten Feder, die auf Dankbarkeit als etwas Schwereloses verweist.",
    christianMeaning:
      "Dankbarkeit als Grundhaltung des Glaubens — nicht abhängig von den Umständen, sondern eine bewusste Antwort auf Gottes Treue.",
    bibleVerse:
      "„Seid dankbar in allen Dingen; denn das ist der Wille Gottes in Christus Jesus für euch.“ — 1. Thessalonicher 5,18",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },

  // ── TIERE & NATUR ────────────────────────────────────────────────
  {
    id: "kuh",
    title: "Kuh",
    image: "Images/IMG_1489.jpeg",
    alt: "Gemälde einer Kuh",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: true,
  },
  {
    id: "weisses-pferd",
    title: "Weißes Pferd",
    image: "Images/IMG_1202.jpeg",
    alt: "Gemälde eines weißen Pferdes",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Das weiße Pferd trägt seit jeher Konnotationen von Reinheit und einer Kraft, die in Ruhe liegt.",
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "highland-rind",
    title: "Highland Rind",
    image: "Images/IMG_1210.jpeg",
    alt: "Gemälde eines schottischen Hochlandrindes",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "hase-im-mondlicht",
    title: "Hase im Mondlicht",
    image: "Images/IMG_1124.jpeg",
    alt: "Gemälde eines Hasen im Mondlicht",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "wilder-hase",
    title: "Wilder Hase",
    image: "Images/IMG_1225.jpeg",
    alt: "Gemälde eines wilden Hasen",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "zwei-hasen",
    title: "Zwei Hasen",
    image: "Images/FullSizeRender.jpeg",
    alt: "Gemälde von zwei Hasen",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "koeniglicher-hund",
    title: "Königlicher Hund",
    image: "Images/IMG_1116 2.jpeg",
    alt: "Gemälde eines Hundes in königlicher Haltung",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: true,
  },
  {
    id: "weisse-kuh",
    title: "Weiße Kuh",
    image: "Images/IMG_1175.jpeg",
    alt: "Gemälde einer weißen Kuh",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "hahn",
    title: "Hahn",
    image: "Images/IMG_4225.jpg",
    alt: "Gemälde eines Hahns mit rotem Kamm und violett-grauem, zerzaustem Gefieder vor grauem Hintergrund",
    year: "2026",
    category: "tiere",
    categoryLabel: "Tiere & Natur",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism:
      "Der wache, direkte Blick des Hahns und sein aufgestellter Kamm stehen für Wachsamkeit und den Anbruch eines neuen Tages.",
    christianMeaning:
      "Der Hahn erinnert an die Verleugnung des Petrus und den Ruf zur Umkehr — und zugleich, mit dem Krähen am Morgen, an einen neuen Anfang.",
    bibleVerse:
      "„Und alsbald krähte der Hahn. Da gedachte Petrus an das Wort Jesu.“ — Matthäus 26,74-75",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },

  // ── PORTRÄT & STILLE MOMENTE ─────────────────────────────────────
  {
    id: "ballerina",
    title: "Ballerina",
    image: "Images/IMG_1152.jpeg",
    alt: "Gemälde einer Ballerina",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "stille",
    title: "Stille",
    image: "Images/IMG_1150.jpeg",
    alt: "Gemälde mit dem Titel Stille",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: "„Seid stille und erkennet, dass ich Gott bin.“ — Psalm 46,11",
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "angesicht",
    title: "Angesicht",
    image: "Images/IMG_1164.jpeg",
    alt: "Gemälde mit dem Titel Angesicht",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "la-rose",
    title: "La Rose",
    image: "Images/IMG_1215.jpeg",
    alt: "Gemälde mit dem Titel La Rose",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: PLACEHOLDER.technique,
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "rosenranke",
    title: "Rosenranke",
    image: "Images/IMG_5196.jpg",
    alt: "Gemälde von drei cremefarbenen Rosen an einer diagonal verlaufenden Ranke mit dunklen, mauvefarbenen Blättern",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "rosenstrauss",
    title: "Rosenstrauß",
    image: "Images/IMG_5198.jpg",
    alt: "Gemälde eines Straußes aus drei mauvefarbenen Rosen mit dunklen Blättern vor grauem Hintergrund",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "rosengeaest",
    title: "Rosengeäst",
    image: "Images/IMG_5199.jpg",
    alt: "Gemälde eines ausladenden Astwerks mit mehreren grau-mauvefarbenen Rosen unterschiedlicher Größe",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "magnolie",
    title: "Magnolie",
    image: "Images/IMG_5200.jpg",
    alt: "Gemälde einer Magnolienblüte in Grau- und Cremetönen vor Blattgold-Streifen",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl und Blattgold auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "rosengold",
    title: "Rosengold",
    image: "Images/IMG_5201.jpg",
    alt: "Gemälde zweier großer mauvefarbener Rosen mit Knospen vor einem Hintergrund mit Blattgold-Streifen und Goldsprenkeln",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl und Blattgold auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
  {
    id: "rosenbluete",
    title: "Rosenblüte",
    image: "Images/IMG_5206.jpg",
    alt: "Gemälde einer einzelnen großen mauvefarbenen Rosenblüte mit goldenem Blütenzentrum auf cremefarbenem Grund",
    year: "2026",
    category: "portrait",
    categoryLabel: "Porträt & Stille Momente",
    technique: "Acryl auf Leinwand",
    dimensions: PLACEHOLDER.dimensions,
    background: PLACEHOLDER.background,
    symbolism: PLACEHOLDER.symbolism,
    christianMeaning: PLACEHOLDER.christianMeaning,
    bibleVerse: PLACEHOLDER.bibleVerse,
    interpretation: PLACEHOLDER.interpretation,
    availability: "Auf Anfrage",
    featured: false,
  },
];

const ARTWORK_CATEGORIES = [
  { key: "all", label: "Alle Werke" },
  { key: "glaube", label: "Glaube & Symbolik" },
  { key: "tiere", label: "Tiere & Natur" },
  { key: "portrait", label: "Porträt & Stille Momente" },
];
